### ISSUE TITLE
Attempting to save unmodified user object results in an error

### ISSUE THREAD

**Issue by sam-wheat** [microsoftgraph/microsoft-graph-explorer-api#413] opened 2021-01-11 15:26 UTC
In the test method below I retrieve a user then try to save it back to the db without making any changes. This results in an exception. The problem here is that I need to be able to update some columns on my own schema (see `USER_FIELDS` below).  How do I do that?

Thanks

See also:
https://github.com/MicrosoftDocs/azure-docs/issues/53168
https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http
Please redirect me if this is not the correct place to raise this issue.

### Expected behavior

The un-modified user object is saved.

### Actual behavior

Message: 
    Test method UpdateUserTest threw exception: 
    Microsoft.Graph.ServiceException: Code: Request_BadRequest
    Message: Adding a non-federated user signInType is not permitted if the user only has social/federated identities or no identities set. Please recreate the user with a non-federated identity along with existing identities if any.
    Inner error:
    	AdditionalData:
    	date: 2021-01-05T02:57:58
    	request-id: 046d86a3-9e8f-4bd1-9d4f-e2c7e8e6a03d
    	client-request-id: 046d86a3-9e8f-4bd1-9d4f-e2c7e8e6a03d
    ClientRequestId: 046d86a3-9e8f-4bd1-9d4f-e2c7e8e6a03d
	

### Steps to reproduce the behavior

        [TestMethod]
        public async Task UpdateUserTest2()
        {
            string userID = "a00afd9b-af51-4206-bd9f-2621343bc70d";
            User user = (await graphService.FindUser(userID)).First();
	        // Don't modify anything.  Just save it again.
            await graphService.UpdateUser(user);
        }
		
		
		
		
		
		private string USER_FIELDS = $"id, userprincipalname, mail, displayname, mailnickname, accountenabled, identities, othermails, {UserAttributes.BillingID}, {UserAttributes.IsBanned}, {UserAttributes.IsCorporateAdmin}, {UserAttributes.IsOptIn}, {UserAttributes.PaymentProviderCustomerID}, {UserAttributes.SuspendedUntil}";
		
        public async Task<List<User>> FindUser(string id)
        {
            var page = client.Users.Request()
                 .Select(USER_FIELDS);

            if (!string.IsNullOrEmpty(id))
                page = page.Filter($"id eq '{id}'");

            List<User> users = null;
            try
            {
                users = (await page.GetAsync())?.ToList();
            }
            catch (Microsoft.Graph.ServiceException)
            {

            }
            return users;
        }
		
		
		
        public async Task UpdateUser(User user)
        {
            var result = await client.Users[user.Id]
            .Request()
            .UpdateAsync(user);
        }

**Comment by MIchaelMainer** [comment] 2021-01-11 18:00
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/868. Please reopen the other issue you created on this.

**Closed by MIchaelMainer** 2021-01-11 18:00 UTC

**Comment by sam-wheat** [comment] 2021-01-11 19:35
@MIchaelMainer 
> I don't have an answer for this service API question. 
Why do you respond if you don't have an answer?  Your comment leads me believe the ticket is in the wrong repo.

**Comment by MIchaelMainer** [comment] 2021-01-11 22:01
@sam-wheat  It looked like a service API issue until after you provided more information. The additional information helped me provide an answer from the perspective of the client. 

I closed this issue since this repo is not for the service API.
